export const GENRE_NAMES = {
    ACTION: "Hành động",
    ADVENTURE: "Phiêu lưu",
    ANIMATION: "Hoạt hình",
    COMEDY: "Hài",
    CRIME: "Tội phạm",
    DRAMA: "Chính kịch",
    FANTASY: "Giả tưởng",
    HISTORICAL: "Lịch sử",
    HORROR: "Kinh dị",
    MYSTERY: "Bí ẩn",
    ROMANCE: "Lãng mạn",
    SCI_FI: "Khoa học viễn tưởng",
    THRILLER: "Giật gân",
    WAR: "Chiến tranh",
    WESTERN: "Viễn tây",
    DARK_COMEDY: "Hài đen",
    DOCUMENTARY: "Tài liệu",
    MUSICAL: "Nhạc kịch",
    SPORTS: "Thể thao",
    SUPERHERO: "Siêu anh hùng",
    PSYCHOLOGICAL_THRILLER: "Kinh dị tâm lý",
    SLASHER: "Kinh dị chém giết",
    BIOPIC: "Tiểu sử",
    NOIR: "Tội phạm noir",
    FAMILY: "Gia đình",
};

export function getGenreColor(genre) {
    const colors = {
        ACTION: "bg-red-500",
        ADVENTURE: "bg-emerald-500",
        ANIMATION: "bg-green-500",
        COMEDY: "bg-yellow-500",
        CRIME: "bg-red-800",
        DRAMA: "bg-purple-500",
        FANTASY: "bg-indigo-500",
        HISTORICAL: "bg-orange-700",
        HORROR: "bg-black",
        MYSTERY: "bg-gray-700",
        ROMANCE: "bg-pink-500",
        SCI_FI: "bg-blue-500",
        THRILLER: "bg-orange-500",
        WAR: "bg-red-600",
        WESTERN: "bg-amber-800",
        DARK_COMEDY: "bg-lime-700",
        DOCUMENTARY: "bg-gray-500",
        MUSICAL: "bg-pink-400",
        SPORTS: "bg-teal-600",
        SUPERHERO: "bg-cyan-600",
        PSYCHOLOGICAL_THRILLER: "bg-fuchsia-700",
        SLASHER: "bg-rose-800",
        BIOPIC: "bg-sky-700",
        NOIR: "bg-stone-800",
        FAMILY: "bg-green-400",
    };

    return colors[genre] || "bg-gray-400";
}
