export const GENRE_NAMES = {
    ACTION: "Hành động",
    ADVENTURE: "Phiêu lưu",
    ANIMATION: "Hoạt hình",
    COMEDY: "Hài",
    CRIME: "Tội phạm",
    DRAMA: "Chính kịch",
    FANTASY: "Giả tưởng",
    HISTORICAL: "Lịch sử",
    HORROR: "Kinh dị",
    MYSTERY: "Bí ẩn",
    ROMANCE: "Lãng mạn",
    SCI_FI: "Khoa học viễn tưởng",
    THRILLER: "Giật gân",
    WAR: "Chiến tranh",
    WESTERN: "Viễn tây",
    DARK_COMEDY: "Hài đen",
    DOCUMENTARY: "Tài liệu",
    MUSICAL: "Nhạc kịch",
    SPORTS: "Thể thao",
    SUPERHERO: "Siêu anh hùng",
    PSYCHOLOGICAL_THRILLER: "Kinh dị tâm lý",
    SLASHER: "Kinh dị chém giết",
    BIOPIC: "Tiểu sử",
    NOIR: "Tội phạm noir",
    FAMILY: "Gia đình",
};

export function getGenreColor(genre) {
    const colors = {
        ACTION: "bg-red-500 text-white",
        ADVENTURE: "bg-emerald-500 text-white",
        ANIMATION: "bg-green-500 text-white",
        COMEDY: "bg-yellow-400 text-black",
        CRIME: "bg-red-800 text-white",
        DRAMA: "bg-purple-500 text-white",
        FANTASY: "bg-indigo-500 text-white",
        HISTORICAL: "bg-orange-700 text-white",
        HORROR: "bg-black text-white",
        MYSTERY: "bg-gray-700 text-white",
        ROMANCE: "bg-pink-500 text-white",
        SCI_FI: "bg-blue-500 text-white",
        THRILLER: "bg-orange-500 text-white",
        WAR: "bg-red-600 text-white",
        WESTERN: "bg-amber-800 text-white",
        DARK_COMEDY: "bg-lime-700 text-white",
        DOCUMENTARY: "bg-gray-500 text-white",
        MUSICAL: "bg-pink-400 text-black",
        SPORTS: "bg-teal-600 text-white",
        SUPERHERO: "bg-cyan-600 text-white",
        PSYCHOLOGICAL_THRILLER: "bg-fuchsia-700 text-white",
        SLASHER: "bg-rose-800 text-white",
        BIOPIC: "bg-sky-700 text-white",
        NOIR: "bg-stone-800 text-white",
        FAMILY: "bg-green-400 text-black",
    };

    return colors[genre] || "bg-gray-400 text-black";
}

